server:
  port: 9091        # Port where your Greet service runs

spring:
  application:
    name: Greet-Services   # Service name
  boot:
    admin:
      client:
        url: http://localhost:1112   # URL of the Admin server

management:
  endpoints:
    web:
      exposure:
        include: '*'  # Expose all actuator endpoints
